/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chord;

import chord.operation.ChordFileSearch;
import chord.operation.FileDownloadUtility;
import java.awt.Color;
import java.awt.Container;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import static chord.Sender.data;

public class ChordMainFrame extends JFrame {

    String resMsg;
    Node node;
    ChordFileSearch chordFileSearch;
    long[] keyList;
    List<String> fileList;
    private Map<String, List<Finger>> keys = new HashMap<>();
    public ChordMainFrame() {
        initComponents();
        lblJoinStatus.setText("");

        DefaultListModel listModel = new DefaultListModel();
        fileList = new ArrayList<>();

        ArrayList<String> zNames = new ArrayList<>();
        try {

            File myObj = new File(new File("").getAbsolutePath()+"\\src\\main\\resources\\FileNames.txt");

            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                zNames.add(data);
        }
        myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        Random rand = new Random();
        Collections.shuffle(zNames);
        int size = rand.nextInt(5)+ 1;
        keyList = new long[size];
        for(int i = 0; i < size ; i++)
        {
            listModel.addElement(zNames.get(i));
            fileList.add(zNames.get(i));
            keyList[i] = new SHA1Hasher(zNames.get(i)).getLong();
        }
        lstSharedFiles.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
      jMenuBar1 = new JMenuBar();
      jMenu1 = new JMenu();
      viewMenu = new JMenu();
      menuItemFingerTable = new JMenuItem();
      menuItemFileKeys = new JMenuItem();
      jLabel1 = new JLabel();
      jSeparator1 = new JSeparator();
      jLabel2 = new JLabel();
      jLabel3 = new JLabel();
      jLabel4 = new JLabel();
      jLabel5 = new JLabel();
      txtUsername = new JTextField();
      txtIP = new JTextField();
      txtPort = new JTextField();
      jLabel6 = new JLabel();
      txtBSIP = new JTextField();
      jLabel7 = new JLabel();
      txtBSPort = new JTextField();
      jLabel8 = new JLabel();
      txtISPort = new JTextField();
      txtISIP = new JTextField();
      jLabel9 = new JLabel();
      jSeparator2 = new JSeparator();
      jSeparator3 = new JSeparator();
      jLabel10 = new JLabel();
      jScrollPane1 = new JScrollPane();
      lstSharedFiles = new JList<>();
      lblJoinStatus = new JLabel();
      btnJoin = new JButton();
      btnLeave = new JButton();
      jLabel11 = new JLabel();
      jSeparator4 = new JSeparator();
      txtFileName = new JTextField();
      btnSearch = new JButton();
      jSeparator5 = new JSeparator();
      progressBar = new JProgressBar();
      btnDownload = new JButton();
      jScrollPane3 = new JScrollPane();
      tblSearchResults = new JTable();
      jLabel12 = new JLabel();
      txtDownloadFolder = new JTextField();
      btnSetFolder = new JButton();

      //======== this ========
      setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);
      Container contentPane = getContentPane();

      //======== jMenuBar1 ========
      {

        //======== jMenu1 ========
        {
          jMenu1.setText("File");
        }
        jMenuBar1.add(jMenu1);

        //======== viewMenu ========
        {
          viewMenu.setText("View");

          //---- menuItemFingerTable ----
          menuItemFingerTable.setText("Finger Table");
          menuItemFingerTable.addActionListener(e -> menuItemFingerTableActionPerformed(e));
          viewMenu.add(menuItemFingerTable);

          //---- menuItemFileKeys ----
          menuItemFileKeys.setText("File keys");
          menuItemFileKeys.addActionListener(e -> menuItemFileKeysActionPerformed(e));
          viewMenu.add(menuItemFileKeys);
        }
        jMenuBar1.add(viewMenu);
      }
      setJMenuBar(jMenuBar1);

      //---- jLabel1 ----
      jLabel1.setText("Cascade");

      //---- jLabel2 ----
      jLabel2.setText("Set Configuraton Details");

      //---- jLabel3 ----
      jLabel3.setText("Username");

      //---- jLabel4 ----
      jLabel4.setText("IP Address");

      //---- jLabel5 ----
      jLabel5.setText("Port");

      //---- txtIP ----
      txtIP.setText("127.0.0.1");

      //---- txtPort ----
      txtPort.addActionListener(e -> txtPortActionPerformed(e));

      //---- jLabel6 ----
      jLabel6.setText("BS IP Address");

      //---- txtBSIP ----
      txtBSIP.setText("127.0.0.1");
      txtBSIP.setEnabled(false);

      //---- jLabel7 ----
      jLabel7.setText("BS Port");

      //---- txtBSPort ----
      txtBSPort.setText("55555");
      txtBSPort.setEnabled(false);
      txtBSPort.addActionListener(e -> txtBSPortActionPerformed(e));

      //---- jLabel8 ----
      jLabel8.setText("Index Server IP Address");

      //---- txtISPort ----
      txtISPort.setText("4444");
      txtISPort.setEnabled(false);
      txtISPort.addActionListener(e -> txtISPortActionPerformed(e));

      //---- txtISIP ----
      txtISIP.setText("127.0.0.1");
      txtISIP.setEnabled(false);

      //---- jLabel9 ----
      jLabel9.setText("Index Server Port");

      //---- jLabel10 ----
      jLabel10.setText("Shared Files");

      //======== jScrollPane1 ========
      {
        jScrollPane1.setViewportView(lstSharedFiles);
      }

      //---- lblJoinStatus ----
      lblJoinStatus.setText("d");

      //---- btnJoin ----
      btnJoin.setText("Join the Network");
      btnJoin.addActionListener(e -> btnJoinActionPerformed(e));

      //---- btnLeave ----
      btnLeave.setText("Leave the Network");
      btnLeave.addActionListener(e -> btnLeaveActionPerformed(e));

      //---- jLabel11 ----
      jLabel11.setText("File Name");

      //---- txtFileName ----
      txtFileName.addActionListener(e -> txtFileNameActionPerformed(e));

      //---- btnSearch ----
      btnSearch.setText("Search");
      btnSearch.addActionListener(e -> btnSearchActionPerformed(e));

      //---- btnDownload ----
      btnDownload.setText("Download");
      btnDownload.addActionListener(e -> btnDownloadActionPerformed(e));

      //======== jScrollPane3 ========
      {

        //---- tblSearchResults ----
        tblSearchResults.setModel(new DefaultTableModel(
          new Object[][] {
            {null, null},
            {null, null},
            {null, null},
            {null, null},
          },
          new String[] {
            "File Name", "Peer Count"
          }
        ) {
          Class<?>[] columnTypes = new Class<?>[] {
            String.class, String.class
          };
          boolean[] columnEditable = new boolean[] {
            false, true
          };
          @Override
          public Class<?> getColumnClass(int columnIndex) {
            return columnTypes[columnIndex];
          }
          @Override
          public boolean isCellEditable(int rowIndex, int columnIndex) {
            return columnEditable[columnIndex];
          }
        });
        jScrollPane3.setViewportView(tblSearchResults);
      }

      //---- jLabel12 ----
      jLabel12.setText("Download Folder");

      //---- txtDownloadFolder ----
      txtDownloadFolder.addActionListener(e -> txtDownloadFolderActionPerformed(e));

      //---- btnSetFolder ----
      btnSetFolder.setText("Set Folder");
      btnSetFolder.addActionListener(e -> btnSetFolderActionPerformed(e));

      GroupLayout contentPaneLayout = new GroupLayout(contentPane);
      contentPane.setLayout(contentPaneLayout);
      contentPaneLayout.setHorizontalGroup(
        contentPaneLayout.createParallelGroup()
          .addComponent(jSeparator1, GroupLayout.Alignment.TRAILING)
          .addGroup(contentPaneLayout.createSequentialGroup()
            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
              .addComponent(jSeparator2, GroupLayout.Alignment.LEADING)
              .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                  .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
                  .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPort, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
                  .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIP, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
                  .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                    .addComponent(txtBSIP, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                  .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                  .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addGap(107, 107, 107)
                    .addComponent(txtFileName)))
                .addGap(2, 2, 2)))
            .addGroup(contentPaneLayout.createParallelGroup()
              .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createParallelGroup()
                  .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addComponent(btnSearch, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                  .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addGap(71, 71, 71))))
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup()
                  .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(contentPaneLayout.createParallelGroup()
                      .addComponent(btnLeave, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(btnJoin, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(lblJoinStatus, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownload, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())))
          .addComponent(jSeparator4)
          .addComponent(jSeparator5)
          .addGroup(contentPaneLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(progressBar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(contentPaneLayout.createSequentialGroup()
            .addGroup(contentPaneLayout.createParallelGroup()
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup()
                  .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(jLabel1))
                  .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel2))
                  .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                      .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBSPort, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))
                      .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(57, 57, 57)
                        .addComponent(txtISPort))
                      .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtISIP, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE))))
                  .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDownloadFolder, GroupLayout.PREFERRED_SIZE, 233, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSetFolder, GroupLayout.PREFERRED_SIZE, 192, GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      contentPaneLayout.setVerticalGroup(
        contentPaneLayout.createParallelGroup()
          .addGroup(contentPaneLayout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel1)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 5, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(btnJoin))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(txtIP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(lblJoinStatus))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(txtPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(btnLeave))
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(contentPaneLayout.createParallelGroup()
              .addComponent(jLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel10)
              .addComponent(txtBSIP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(contentPaneLayout.createParallelGroup()
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                  .addComponent(txtBSPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel7))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel8)
                  .addComponent(txtISIP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel9)
                  .addComponent(txtISPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
              .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel11)
              .addComponent(txtFileName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
              .addComponent(btnSearch))
            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(contentPaneLayout.createParallelGroup()
              .addGroup(contentPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel12)
                  .addComponent(txtDownloadFolder, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                  .addComponent(btnSetFolder))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
              .addComponent(btnDownload))
            .addGap(18, 18, 18))
      );
      pack();
      setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFingerTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFingerTableActionPerformed
        FingerTableFrame fingerView = new FingerTableFrame();
        fingerView.setData(node.getId(), node.getFingers());
        fingerView.setVisible(true);
        fingerView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuItemFingerTableActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void txtBSPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBSPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBSPortActionPerformed

    private void txtISPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISPortActionPerformed

    private void txtFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileNameActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        HostConfiguration.BOOTSTRAP_IP = txtBSIP.getText();
        HostConfiguration.BOOTSTRAP_PORT = Integer.valueOf(txtBSPort.getText());
        HostConfiguration.MY_IP = txtIP.getText();
        HostConfiguration.MY_NAME = txtUsername.getText();
        HostConfiguration.MY_PORT = Integer.valueOf(txtPort.getText());

        RegisterResponse regRes = register();
        if(!regRes.isInitialNode())
        {
            node = new Node(txtIP.getText(), txtPort.getText(), regRes.getPeerIps(), regRes.getpeerPorts());
        }
        else
        {
            node = new Node(txtIP.getText(), txtPort.getText());
        }

        lblJoinStatus.setText(resMsg);

        //Message String creation
        String message = "ADD:";

        message = message + String.join(":", fileList);

        for(int i = 0; i < keyList.length; i++)
        {
            List<Finger> lst = new ArrayList<>();
            lst.add(new Finger(txtIP.getText(), Integer.valueOf(txtPort.getText())));
            keys.put(keyList[i]+"", lst);

            //message.concat(keyList[i]+":");
        }


        node.setKeys(keys);

        chordFileSearch = new ChordFileSearch(node);


        //publish to index server
        InetAddress IPAddress1;
        try {
            DatagramSocket socket= new DatagramSocket();
            byte[] toSend1  = message.getBytes();
            IPAddress1 = InetAddress.getByName(txtISIP.getText());
            DatagramPacket packet =new DatagramPacket(toSend1, toSend1.length, IPAddress1, Integer.parseInt(txtISPort.getText()));
            socket.send(packet);
        } catch (UnknownHostException ex) {
            Logger.getLogger(NodeStabilizer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChordMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try
        {
            DefaultTableModel searchResultsDataModel = (DefaultTableModel) tblSearchResults.getModel();

            while (searchResultsDataModel.getRowCount()>0)
            {
               searchResultsDataModel.removeRow(0);
            }

            //Contact Index Server and Get Node List
            String fileQuery = txtFileName.getText().trim();
            String searchMessage = "SER:"+fileQuery;

            DatagramSocket socket = new DatagramSocket();
            byte[] toSend  = searchMessage.getBytes();
            InetAddress IPAddress;
                try {
                    IPAddress = InetAddress.getByName(txtISIP.getText());
                    DatagramPacket packet =new DatagramPacket(toSend, toSend.length, IPAddress, Integer.valueOf(txtISPort.getText()));
                    try {
                        socket.send(packet);
                    } catch (IOException ex) {
                        Logger.getLogger(ChordThread.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Node.class.getName()).log(Level.SEVERE, null, ex);
                }

            System.out.println("Sent: " + searchMessage);

            byte[] receive = new byte[65535];
            DatagramPacket DpReceive = new DatagramPacket(receive, receive.length);
            try {
                socket.receive(DpReceive);
            } catch (IOException ex) {
                Logger.getLogger(ChordThread.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Read response from chord
            String serverResponse = data(receive).toString();
            System.out.println("Received: " + serverResponse);


            String[] serverResponseSegments = serverResponse.split(":");
            if(serverResponseSegments[0].equals("SEARCH_RES")){

                int searchResultCount = Integer.valueOf(serverResponseSegments[1]);

                int i=2;
                String fileName = "";
                String peerCount = "";

                while(i<serverResponseSegments.length){
                    fileName = serverResponseSegments[i];
                    peerCount = serverResponseSegments[i+1];
                    String[] dataRow = {fileName, peerCount};
                    searchResultsDataModel.addRow(dataRow);
                    i=i+2;
                }

            }

        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        unreg();
        System.exit(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void menuItemFileKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFileKeysActionPerformed
        ChordFileKeyFrame fileKeyFrame = new ChordFileKeyFrame();
        fileKeyFrame.setData(node.getId(), node.getKeys());
        fileKeyFrame.setVisible(true);
        fileKeyFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuItemFileKeysActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        //Get File Save Path
        if(txtDownloadFolder.getText()==null || txtDownloadFolder.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Please select a folder path", "File Download Error", JOptionPane.WARNING_MESSAGE);
            return;
        }


        int selectedRow = tblSearchResults.getSelectedRow();
        if(selectedRow!=-1){
            String fullFileName = tblSearchResults.getModel().getValueAt(selectedRow, 0).toString();
            //String fullFileName = txtFileName.getText()
            List<Finger> peers = chordFileSearch.searchFile(fullFileName);
            if(peers!=null && peers.size()>0)
            {
                List<String> nodeList = new ArrayList<>();
                peers.forEach(peer->{
                    nodeList.add(peer.getAddress()+":"+peer.getPort());
                });
                String peerListStr = String.join(", ", nodeList);
                //JOptionPane.showMessageDialog(null, "File Found at Peers - "+ peerListStr, "File Download", JOptionPane.INFORMATION_MESSAGE);


                int dialogResult = JOptionPane.showConfirmDialog (null, "File Found at Peers - "+ peerListStr+ ". Do you want to download from a random node?","Download Confirmation",JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION){
                    //TODO: Do Download Here
                    int randomNodeId = getRandomIntegerBetweenRange(0, nodeList.size()-1);
                    Finger selectedPeer = peers.get(randomNodeId);
                    int downloadPort = selectedPeer.getPort()+1000;
                    String fileDownloadURL = "http://localhost:"+downloadPort+"/api/download?file="+fullFileName.replaceAll(" ", "");
                    System.out.println("File is Downloading from "+fileDownloadURL+ " to "+txtDownloadFolder.getText());
                    try {
                        FileDownloadUtility.downloadFile(fileDownloadURL, txtDownloadFolder.getText());
                        JOptionPane.showMessageDialog(null, "File downloaded successfuly from node "+selectedPeer.getAddress()+":"+selectedPeer.getPort(), "File Download Successful", JOptionPane.INFORMATION_MESSAGE);

                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "File Not Found", "File Download Error", JOptionPane.WARNING_MESSAGE);
                        ex.printStackTrace();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "File Not Found", "File Download Error", JOptionPane.WARNING_MESSAGE);
                }




            }
            else
                JOptionPane.showMessageDialog(null, "File Not Found", "File Download Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a file to download", "File Download Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void txtDownloadFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDownloadFolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDownloadFolderActionPerformed

    private void btnSetFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetFolderActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int option = fileChooser.showOpenDialog(this);
            if(option == JFileChooser.APPROVE_OPTION){
               File file = fileChooser.getSelectedFile();
               txtDownloadFolder.setText(file.getAbsolutePath());
            }
    }//GEN-LAST:event_btnSetFolderActionPerformed

    public static int getRandomIntegerBetweenRange(int min, int max){
        int x = (int)(Math.random()*((max-min)+1))+min;
        return x;
    }
    //generate SHA/MD5 file checksum
    private static String getFileChecksum(MessageDigest digest, File file) throws IOException
    {
        //Get file input stream for reading the file content
        FileInputStream fis = new FileInputStream(file);

        //Create byte array to read data in chunks
        byte[] byteArray = new byte[1024];
        int bytesCount = 0;

        //Read file data and update in message digest
        while ((bytesCount = fis.read(byteArray)) != -1) {
            digest.update(byteArray, 0, bytesCount);
        };

        //close the stream; We don't need it now.
        fis.close();

        //Get the hash's bytes
        byte[] bytes = digest.digest();

        //This bytes[] has bytes in decimal format;
        //Convert it to hexadecimal format
        StringBuilder sb = new StringBuilder();
        for(int i=0; i< bytes.length ;i++)
        {
            sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
        }

        //return complete hash
       return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ChordMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ChordMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ChordMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ChordMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChordMainFrame().setVisible(true);
            }
        });
    }

    // Register node in super node
    public RegisterResponse register() {
        resMsg = "Failed";
        String message = (new Message(MessageType.REG, txtIP.getText(), Integer.valueOf(txtPort.getText()), txtUsername.getText())).getMessage();
        String response = Sender.getInstance().sendUDPMessage(message, txtBSIP.getText(), Integer.valueOf(txtBSPort.getText()));
        System.out.println("Response:" + response);
        lblJoinStatus.setForeground(Color.RED);
        if ((response.trim()).equals("-1")) {
            resMsg = "Failed";
            return new RegisterResponse(MessageType.REG_FAILURE, null, null);
        } else if ((response.trim()).equals("-2")) {
            resMsg = "Failed";
            unreg();
            return new RegisterResponse(MessageType.REG_FAILURE, null, null);
        } else {
            String[] splitted = response.split(" ");

            String noOfNodes = splitted[2];
            HostConfiguration.myNodeNumber = Integer.parseInt(noOfNodes.trim());
            HostConfiguration.noOfNodes = HostConfiguration.myNodeNumber + 1;

            String[] peerIps;
            int[] peerPorts;

            // System.out.println(noOfNodes);
            switch (noOfNodes.trim()) {
                case "0":
                    resMsg = "Connected";
                    lblJoinStatus.setForeground(Color.GREEN);
                    return new RegisterResponse(MessageType.REG_SUCCESS, null, null);
                // break;
                case "1":
                    peerIps = new String[1];
                    peerPorts = new int[1];
                    peerIps[0] = splitted[3];
                    peerPorts[0] = Integer.parseInt(splitted[4]);
                    lblJoinStatus.setForeground(Color.GREEN);
                    resMsg = "Connected";
                    //  System.out.println(joinNetwork(peerIps[0], peerPorts[0]));
                    return new RegisterResponse(MessageType.REG_SUCCESS, peerIps, peerPorts);
                //  break;
                case "9996":
                    System.out.println("Failed, can’t register. BS full.");
                    resMsg = "Failed, can’t register. BS full.";
                    return new RegisterResponse(MessageType.REG_FAILURE, null, null);
                //     break;
                case "9997":
                    System.out.println("Failed, registered to another user, try a different IP and port");
                    resMsg = "Failed, registered to another user, try a different IP and port.";
                    return new RegisterResponse(MessageType.REG_FAILURE, null, null);
                //  break;
                case "9998":
                    System.out.println("Failed, already registered to you, unregister first");
                    resMsg = "Failed, already registered to you, unregister first.";
                    return new RegisterResponse(MessageType.REG_FAILURE, null, null);
                // break;
                case "9999":
                    System.out.println("Failed, there is some error in the command");
                    resMsg = "Failed, there is some error in the command.";
                    return new RegisterResponse(MessageType.REG_FAILURE, null, null);
                //  break;

                default:
                    peerIps = new String[2];
                    peerPorts = new int[2];

                    peerIps[0] = splitted[3];
                    peerPorts[0] = Integer.parseInt(splitted[4]);

                    peerIps[1] = splitted[5];
                    peerPorts[1] = Integer.parseInt(splitted[6]);

                    lblJoinStatus.setForeground(Color.GREEN);
                    resMsg = "Connected";
                    return new RegisterResponse(MessageType.REG_SUCCESS, peerIps, peerPorts);
            }
        }
    }
    
    private void unreg() {
        String message = (new Message(MessageType.UNREG, txtIP.getText(), Integer.valueOf(txtPort.getText()), txtUsername.getText())).getMessage();
        Sender.getInstance().sendUDPMessage(message, txtBSIP.getText(), Integer.valueOf(txtBSPort.getText()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JMenuBar jMenuBar1;
    private JMenu jMenu1;
    private JMenu viewMenu;
    private JMenuItem menuItemFingerTable;
    private JMenuItem menuItemFileKeys;
    private JLabel jLabel1;
    private JSeparator jSeparator1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField txtUsername;
    private JTextField txtIP;
    private JTextField txtPort;
    private JLabel jLabel6;
    private JTextField txtBSIP;
    private JLabel jLabel7;
    private JTextField txtBSPort;
    private JLabel jLabel8;
    private JTextField txtISPort;
    private JTextField txtISIP;
    private JLabel jLabel9;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JLabel jLabel10;
    private JScrollPane jScrollPane1;
    private JList<String> lstSharedFiles;
    private JLabel lblJoinStatus;
    private JButton btnJoin;
    private JButton btnLeave;
    private JLabel jLabel11;
    private JSeparator jSeparator4;
    private JTextField txtFileName;
    private JButton btnSearch;
    private JSeparator jSeparator5;
    private JProgressBar progressBar;
    private JButton btnDownload;
    private JScrollPane jScrollPane3;
    private JTable tblSearchResults;
    private JLabel jLabel12;
    private JTextField txtDownloadFolder;
    private JButton btnSetFolder;
    // End of variables declaration//GEN-END:variables
}
